Test
kiselevgleb/Notesandreminding pull request #3
Opened 2019-07-18 15:33 UTC by kiselevgleb

Update 17.07.19

2019-07-18 16:19 UTC, ghost requested changes
Старайся сам свой код прям тут в пул реквесте смотреть
Если что-то не понятно самому или увидел недочеты, то сразу же исправляй

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/res/layout/activity_write_notes.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Вот тут нужен `ScrollView`

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/res/layout/list_item.xml
> +        android:id="@android:id/text1"
переименую id для вьюх

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/res/menu/savemenu.xml
> +        android:id="@+id/item2"
тоже id переименовать

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/res/menu/savemenu.xml
> +        android:title="Save"
строку в ресурсы

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +                startActivity(intent2);
Давай лучше из `NotesAct` делать`startActivityForResult` а тут выставлять результат OK и делать `finish()`

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    TextView currentDateTime;
private  все поля

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    EditText text1;
переименую поля в что-то типа title, description, dueDate

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/Notes.java
> +        this.hader = hader;
`header` это заголовок в списке обычно, а у тебя наверное все же `title`

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/Notes.java
> +    Calendar calendar;
прям `Calendar` тут лучше не использовать, храни время в милисекундах в `long`

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/res/layout/activity_write_notes.xml
> +        android:text="Has deadline" />
в ресурсы

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/res/layout/activity_write_notes.xml
> +        />
здесь тоже сделай reformat code

2019-07-18 16:19 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MyAdapter.java
> +public class MyAdapter extends BaseAdapter {
переименовать в что-то более логичное

2019-07-19 14:44 UTC, ghost requested changes
Пройдись по все классам и проверь названия id строки названия полей и тд. Сейчас называется как попало, строки куча в коде, не отформатирован код.

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        SharedPreferences sp = getSharedPreferences("MY_SETTINGS", Context.MODE_PRIVATE);
"MY_SETTINGS" вынести в константы

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
>          super.onCreate(savedInstanceState);
`super.onCreate(savedInstanceState);` должен быть в начале самом

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +            if (pass.length() > 0) {
вот условие не нужно будет если ты сделаешь
```
pass = pass.substring(0, Math.max(0,pass.length() - 1));
check();
```

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        if (pass.length() == 0) {
Сделай первым делом вот это, без всяких условий
```
point1.setTextColor(Color.GRAY);
            point2.setTextColor(Color.GRAY);
            point3.setTextColor(Color.GRAY);
            point4.setTextColor(Color.GRAY);
```
А потом уже if

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        } else if (pass.length() == 4) {
Вот тут у тебя мешанина, 
```
else if (pass.length() == 4) {
            point1.setTextColor(Color.YELLOW);
            point2.setTextColor(Color.YELLOW);
            point3.setTextColor(Color.YELLOW);
            point4.setTextColor(Color.YELLOW);
        }
        if (pass.length() == 4 && pass.equals(sp.getString("777", ""))) {
            Intent intent = new Intent(MainActivity.this, NotesAct.class);
            startActivity(intent);
        } else if (pass.length() == 4) {
            pass = "";
            point1.setTextColor(Color.GRAY);
            point2.setTextColor(Color.GRAY);
            point3.setTextColor(Color.GRAY);
            point4.setTextColor(Color.GRAY);
            Toast.makeText(getApplicationContext(), "Error password", Toast.LENGTH_SHORT).show();
        }
```

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +    public static SharedPreferences sp;
public static тут прям точно не нужно делать

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +        sp = getSharedPreferences("0", Context.MODE_PRIVATE);
Эм, а что за `"0"`

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +                Toast.makeText(getApplicationContext(), "Error password", Toast.LENGTH_SHORT).show();
Текст ошибки поменять на что-то человеко читаемое и в ресурсы его

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +                e.putString("777", p);
Вот это что за магия? `"777"`

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +                startActivity(intent);
вот тут текущую активити закрыть не помешало бы

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/Notes.java
> +public class Notes {
`Note`

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/Notes.java
> +    long calendar;
название переменной выбрано не очень удачно, лучше timeMs

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            intent.putExtra("hader1", item.getKey());
ключи по которым кладешь в константы

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            case R.id.sort:
почему называется sort ?

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                Intent intent2 = new Intent(NotesAct.this, NewPassActivity.class);
почему intent2?

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    public static EditText hader1;
статические поля лучше без необходимости не используй. Через них очень легко получить утечку памяти.

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    TextView currentDateTime;
тут все поля названы очень так себе

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +            case R.id.item2:
имя

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/res/layout/activity_new_pass.xml
> +        android:hint="Pass"
все строки в ресурсы

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/res/values/strings.xml
> +    <string name="Body">Тело заметки</string>
Давай определимся мы на русском или на английском делаем строки по умолчанию?

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    }
сделай автоформат, сейчас пробелы и отступы явно не в порядке

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    ArrayList<HashMap<String, String>> hmList = new ArrayList<>();
Чем раньше ты тут переделаешь, тем меньше кода тебе потом менять придется

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +        floating.setOnClickListener(clickListener);
floating переименовать

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        boolean hasVisited = sp.getBoolean("hasVisited", false);
ключ в константы

2019-07-19 14:44 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +            e.putBoolean("hasVisited", true);
Вот здесь точно баг, ты первый раз когда откроешь приложение то запишешь `true ` но если пользователь не введет новый пароль то потом ты так и будет без пароля сидеть. Тут надо не на наличие флажка проверять а на то есть ли пароль сохраненный или нет

2019-07-19 14:46 UTC, ghost requested changes

2019-07-19 14:46 UTC, grenni2007 commented on app/src/main/AndroidManifest.xml
> +    <!-- To auto-complete the email text field in the login form with the user's emails -->
А без этого что именно не работало? просто это очень важные пермишены

2019-07-22 08:59 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        SharedPreferences sp = getSharedPreferences("MY_SETTINGS", Context.MODE_PRIVATE);
"MY_SETTINGS" вынес в константы

2019-07-22 08:59 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
>          super.onCreate(savedInstanceState);
Перенес

2019-07-22 09:00 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +            if (pass.length() > 0) {
Поправил

2019-07-22 09:00 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        if (pass.length() == 0) {
Поправил

2019-07-22 09:00 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        } else if (pass.length() == 4) {
Поправил, но не уверен, что все

2019-07-22 09:00 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    }
Сделал

2019-07-22 09:02 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +        floating.setOnClickListener(clickListener);
Не совсем понял, что именно надо переделать?
floating переименовал.

2019-07-22 09:02 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        boolean hasVisited = sp.getBoolean("hasVisited", false);
"MY_SETTINGS" добавил в константы

2019-07-22 09:06 UTC, kiselevgleb commented on app/src/main/AndroidManifest.xml
> +    <!-- To auto-complete the email text field in the login form with the user's emails -->
Удалю. Я думаю, что этот код остался после того как я выбирал шаблон Activity Login, потом его удалил и выбрал Activity Empty

2019-07-22 09:14 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        @Override
Поправил

2019-07-22 09:14 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +//    private View.OnClickListener clickListener2 = new View.OnClickListener() {
Удалил

2019-07-22 09:15 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +                point4.setTextColor(Color.GRAY);}
Сделал тост

2019-07-22 09:15 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    private View.OnClickListener clickListener3 = new View.OnClickListener() {
Сделал

2019-07-22 09:15 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        n2.setOnClickListener(clickListener2);
Сделал

2019-07-22 09:19 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    if (pass.length()==4&&pass.equals(passDoc)) {
Поправил, но не уверен что все

2019-07-22 09:20 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        startActivity(intent); }
Закрыл

2019-07-22 09:21 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
>          n1.setOnClickListener(clickListener1);
Тоесть вообще не создавать переменные Button?

2019-07-22 09:22 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    if (pass.length()==0){
Поправил

2019-07-22 09:27 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        point1.setTextColor(Color.YELLOW);
Поправил

2019-07-22 09:28 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
>      String pass = "";
ок

2019-07-22 09:32 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    ArrayList<HashMap<String, String>> hmList = new ArrayList<>();
Пока не нашел решение

2019-07-22 10:59 UTC, kiselevgleb commented on app/src/main/res/layout/activity_write_notes.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Добавил

2019-07-22 11:10 UTC, kiselevgleb commented on app/src/main/res/layout/list_item.xml
> +        android:id="@android:id/text1"
Пробовал несколькими способами, но возникает ошибка((

2019-07-22 11:11 UTC, kiselevgleb commented on app/src/main/res/menu/savemenu.xml
> +        android:id="@+id/item2"
Пробовал несколькими способами, но возникает ошибка((

2019-07-22 11:12 UTC, kiselevgleb commented on app/src/main/res/menu/savemenu.xml
> +        android:id="@+id/item2"
Здесь ОК

2019-07-22 11:15 UTC, kiselevgleb commented on app/src/main/res/menu/savemenu.xml
> +        android:title="Save"
Добавил

2019-07-22 11:19 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +                startActivity(intent2);
Не понял(

2019-07-22 11:35 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    TextView currentDateTime;
Поправил

2019-07-22 11:37 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    EditText text1;
Переименовал

2019-07-22 11:38 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Notes.java
> +        this.hader = hader;
Переименовал

2019-07-22 11:38 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Notes.java
> +    Calendar calendar;
Поправил

2019-07-22 11:39 UTC, kiselevgleb commented on app/src/main/res/layout/activity_write_notes.xml
> +        android:text="Has deadline" />
Добавил

2019-07-22 11:39 UTC, kiselevgleb commented on app/src/main/res/layout/activity_write_notes.xml
> +        />
сделал

2019-07-22 11:40 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MyAdapter.java
> +public class MyAdapter extends BaseAdapter {
Переименовал

2019-07-23 09:34 UTC, ghost requested changes
Давай мы сконцентируем усилия над тем чтобы довести уже существующий код до хорошего состояния. Чем сильнее ты стараешься добавить новый функционал и оставляешь недоделки на потом тем тяжелее их будет исправлять. Так же идея в том что мы в пул реквесте тут проверяем не сразу все задание целиком, а кусками. Как только мы видим что код готов, мы вливаем ветку test в master(это я сделаю когда нажму на пул реквесте что с ним все хорошо) и потом когда код добавляется существующий уже не участвует в дискуссии

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    public void check() {
Смотри, вот этот метод если сделать вот таким, то я думаю он будет лучше намного выглядеть и станет меньше
```kotlin
public void check() {
        int unCheckedColor = getColor(R.color.pointUnChecked);
        point1.setTextColor(unCheckedColor);
        point2.setTextColor(unCheckedColor);
        point3.setTextColor(unCheckedColor);
        point4.setTextColor(unCheckedColor);
        int checkedColor = getColor(R.color.pointChecked);
        if (pass.length() == 1) {
            point1.setTextColor(checkedColor);
        } else if (pass.length() == 2) {
            point1.setTextColor(checkedColor);
            point2.setTextColor(checkedColor);
        } else if (pass.length() == 3) {
            point1.setTextColor(checkedColor);
            point2.setTextColor(checkedColor);
            point3.setTextColor(checkedColor);
        } else if (pass.length() == 4) {
            if(проверка_пароля ){
                finish();
                Intent intent = new Intent(MainActivity.this, NotesAct.class);
                startActivity(intent);
            } else {
                pass = "";
                Toast.makeText(getApplicationContext(), "Error password", Toast.LENGTH_SHORT).show();
            }

        }
    }
```

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        if (pass.length() == 0) {
чуть выше добавил кусок кода

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        @RequiresApi(api = Build.VERSION_CODES.M)
тут тоже RequiresApi не нужно

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
>      private Button n9;
Тебе не нужны поля вот эти 
```
 private Button n1;
    private Button n2;
    private Button n3;
    private Button n4;
    private Button n5;
    private Button n6;
    private Button n7;
    private Button n8;
    private Button n9;
    private Button n0;
    private Button c;
``` 
Вместо этого просто пиши например
```
findViewById(R.id.button1).setOnClickListener(new NumberClickListener(1));
```

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +                Toast.makeText(getApplicationContext(), "Error password", Toast.LENGTH_SHORT).show();
!

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +            finish();
лучше сделай 
```
finish();
``` 
после `startActivity `

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +        eye = (CheckBox) findViewById(R.id.checkBoxPass);
`eye`? может быть `showPasswordCheckbox`

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            case R.id.sort:
!

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                Intent intent2 = new Intent(NotesAct.this, NewPassActivity.class);
!

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +                    startActivity(intent2);
ты уверен что нам нужно делать `startActivity ` а не просто закрыть текущую?

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +                startActivity(intent);
ты уверен что нам нужно делать `startActivity ` а не просто закрыть текущую?

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    TimePickerDialog.OnTimeSetListener t = new TimePickerDialog.OnTimeSetListener() {
переименовать

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    DatePickerDialog.OnDateSetListener d = new DatePickerDialog.OnDateSetListener() {
переименовать

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/res/layout/activity_write_notes.xml
> +    <ScrollView
В ScrollView нужно завернуть весь экран

2019-07-23 09:34 UTC, grenni2007 commented on app/src/main/res/layout/list_item.xml
> +        android:id="@android:id/text1"
А какая ошибка?  попробуй 
```
<TextView
        android:id="@+id/title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="25sp"/>

    <TextView
        android:id="@+id/subtitle"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
```

2019-07-23 10:46 UTC, kiselevgleb commented on app/src/main/res/layout/list_item.xml
> +        android:id="@android:id/text1"
Ок, получилось

2019-07-23 10:50 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +    public static SharedPreferences sp;
Удалил

2019-07-23 10:53 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +        sp = getSharedPreferences("0", Context.MODE_PRIVATE);
Это временный KEY, чтобы инициировать переменную. Заменил на temp

2019-07-23 11:01 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +                Toast.makeText(getApplicationContext(), "Error password", Toast.LENGTH_SHORT).show();
Добавил

2019-07-23 11:02 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +                e.putString("777", p);
Поправил

2019-07-23 11:03 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +                startActivity(intent);
Закрыл

2019-07-23 11:04 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Notes.java
> +public class Notes {
Поправил

2019-07-23 11:05 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            intent.putExtra("hader1", item.getKey());
Добавил дату

2019-07-23 11:09 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            case R.id.sort:
Переименовал NewPass

2019-07-23 11:10 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                Intent intent2 = new Intent(NotesAct.this, NewPassActivity.class);
Поправил

2019-07-23 11:10 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    public static EditText hader1;
Поправил

2019-07-23 11:12 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +            case R.id.item2:
Поправил

2019-07-23 11:14 UTC, kiselevgleb commented on app/src/main/res/layout/activity_new_pass.xml
> +        android:hint="Pass"
Поправил

2019-07-23 11:15 UTC, kiselevgleb commented on app/src/main/res/values/strings.xml
> +    <string name="Body">Тело заметки</string>
Поправил

2019-07-23 11:16 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +            e.putBoolean("hasVisited", true);
Поправил

2019-07-23 11:18 UTC, kiselevgleb commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
Удалил

2019-07-23 11:35 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    private static SharedPreferences spass;
Добавил

2019-07-23 11:40 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        @RequiresApi(api = Build.VERSION_CODES.M)
IDEA автоматически добавила, если убираю то возникает ошибка при вызове метода check() - getColor()

2019-07-23 12:09 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    TimePickerDialog.OnTimeSetListener t = new TimePickerDialog.OnTimeSetListener() {
Переименовал

2019-07-23 12:10 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    DatePickerDialog.OnDateSetListener d = new DatePickerDialog.OnDateSetListener() {
Переименовал

2019-07-23 12:13 UTC, kiselevgleb commented on app/src/main/res/layout/activity_write_notes.xml
> +    <ScrollView
ок

2019-07-24 07:08 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +            finish();
Сделал

2019-07-24 07:10 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
>      private Button n9;
ок

2019-07-24 07:12 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +        eye = (CheckBox) findViewById(R.id.checkBoxPass);
ок

2019-07-24 15:18 UTC, ghost requested changes
Стало прям сильно лучше, но осталось еще пару мест где у нас прям не очень хорошо(
1. Я так и не понял что за ключ у нас в map
2. флажек который мы то ставим 0 то 1 нужно убрать и передавать на экран через параметры
3. Огромный метод на экране редактирования

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                intent.putExtra("haderEditText", note.getTitle());
ключи под которыми ты тут кладешь должны быть в `WriteNotesActivity`
```public static final String EXTRA_HEADER = "header"; ```
все причем

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                String timeString = " ";
А расскажи что тут происходит, выглядит как что-то очень странное(((
```
String timeString = " ";
                if (item.getKey() != 0) {
                    Calendar d = Calendar.getInstance();
                    d.setTimeInMillis(item.getKey());
                    Date convertDate = d.getTime();
                    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yy hh:mm");
                    timeString = formatter.format(convertDate);
                }
```

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    public void showNotes(HashMap<Long, Note> not) {
ты уверен что нужен public?

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    private View.OnClickListener clickListener = new View.OnClickListener() {
назвать как-то по другому, клик листенер на что это?

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
>          inflater.inflate(R.menu.notmenu, menu);
notes_activity_menu лучше может быть?

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            case R.id.newPass:
id в меню пишутся `new_pass_action` обычно

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                finish();
сначала startActivity потом finish

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/SettingsManager.java
> +public class SettingsManager {
Как тебе идея?

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    public boolean onOptionsItemSelected(MenuItem item) {
когда метод не влазиет на 1 экран по высоте это признак того что надо что-то с ним делать

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    DatePickerDialog.OnDateSetListener dateDialog = new DatePickerDialog.OnDateSetListener() {
название dateSetListener

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    TimePickerDialog.OnTimeSetListener timeDialog = new TimePickerDialog.OnTimeSetListener() {
timeSetListener

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/res/layout/activity_write_notes.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
теперь осталось избавиться от корневого LinearLayout так как в нем ничего полезного нет, то есть корневым элементом должен быть сразу scrollView

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    public static int impText = 0;
Я наконец отгадал что это такое)))) Передавай на экран редактирования этот флажек через extras не делай static переменных

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    public static HashMap<Long, Note> getDateBase() {
Давай сделаем класс 
```
public class NotesRepository{
      private static HashMap<Long, Note> notes = new HashMap<>();
      public HashMap<Long, Note> getNotes(){
             return notes
      }

      public void removeNote

      public void saveNote

      public void createNote
}
```
и им будут пользоваться все кому нужно что-то сделать с этими notes

2019-07-24 15:18 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    private static HashMap<Long, Note> dateBase = new HashMap<>();
для меня до сих пор загадка что является ключем?

2019-07-25 07:18 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        @RequiresApi(api = Build.VERSION_CODES.M)
Добавил

2019-07-25 07:44 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +            if (pass.length() == 4 && pass.equals(settingsManager.getPinCode())) {
Удалил

2019-07-25 07:44 UTC, kiselevgleb commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_PROFILE" />
Удалил

2019-07-25 07:45 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +    EditText pass;
Добавил private

2019-07-25 07:46 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +    private String VALUE_SP = "PrivateValue";
Удалил

2019-07-25 07:49 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +//            finish();
Добавил

2019-07-25 08:02 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Note.java
> +    String calendar;
Поменял на long

2019-07-25 08:45 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    FloatingActionButton add;
Добавил private

2019-07-25 08:45 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    ListView listView;
Добавил private

2019-07-25 08:49 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    long key = 0;
Удалил. Не совсем понял почему IDEA попросила key сделать final(

2019-07-25 08:50 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            key = item.getKey();
Сделал. Почему final?

2019-07-25 08:51 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                    Intent intent = new Intent(NotesAct.this, NotesAct.class);
Чтобы обновить список после удаления пункта, в противном случае удаленный пункт остается

2019-07-25 08:54 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            AlertDialog.Builder builder = new AlertDialog.Builder(NotesAct.this);
Поправил. У Builder вызов похож на Stream

2019-07-25 09:20 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                intent.putExtra("haderEditText", note.getTitle());
Не понял. 
1. ключи под которыми ты тут кладешь должны быть в WriteNotesActivity - ключи есть в WriteNotesActivity и данные передаются.
2. Тогда тут ты будешь передавать id , а на след экране делать - Новый экран все равно же создавать нужно будет и в любом случае передавать данные а именно id параметр.

2019-07-25 09:26 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                String timeString = " ";
Немного поправил метод, проверка на ноль уже не нужна. А остальной код конвертирует long key в String чтобы передать в  WriteNotesActivity как предзаполненое поле дата.

2019-07-25 09:28 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    public void showNotes(HashMap<Long, Note> not) {
Изменил на private

2019-07-25 09:30 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    private View.OnClickListener clickListener = new View.OnClickListener() {
Переименовал на addNoteClickListener

2019-07-25 09:35 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
>          inflater.inflate(R.menu.notmenu, menu);
Переименовал

2019-07-25 09:36 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            case R.id.newPass:
Переименовал

2019-07-25 09:40 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                finish();
Поправил

2019-07-25 09:42 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/SettingsManager.java
> +public class SettingsManager {
Удобно, раньше не пользовался

2019-07-25 09:52 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    public boolean onOptionsItemSelected(MenuItem item) {
Попробую здесь что-то сделать... ps куплю монитор побольше))

2019-07-25 09:54 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    DatePickerDialog.OnDateSetListener dateDialog = new DatePickerDialog.OnDateSetListener() {
Поправил

2019-07-25 09:54 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +    TimePickerDialog.OnTimeSetListener timeDialog = new TimePickerDialog.OnTimeSetListener() {
Поправил

2019-07-25 10:28 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    public static int impText = 0;
Сделал

2019-07-25 13:20 UTC, ghost requested changes
Давай мы сначала поправим все кроме WriteNotesActivity

2019-07-25 13:20 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +public class NotesRepository {
Наконец-то я понял что ты тут делаешь и что является ключем. Давай внутри использовать Map как ты и хотел, но возвращать наружу список
```

public class NotesRepository {

    private Map<Long, Note> notes = new HashMap<>();

    private int lastUsedId = 0;

    public static final NotesRepository INSTANCE = new NotesRepository();// делаешь себе в activity поле и в него в onCreate кладешь NotesRepository.INSTANCE

    public List<Note> getSortedNotes() {
        //тут нам нужно логику сортировки сделать, пока можешь просто заметки все вернуть и все
    }

    public void removeNote(Long noteId) {
        notes.remove(noteId);
    }

    public void saveNote(Note note) {
        final Long id = note.getId();
        // нужно в note еще добавить поле lastUpdatedTime тоже long и тут его обновлять
        if (id == null) {
            note.setId(generateNewId());
            // тут просто в конец списка добавляем
        } else {
            notes.put(id, note);
            // ищем в списке notes элемент с таким id
            // его удаляем а note на его позицию вставляем
        }
    }

    private int generateNewId() {
        return lastUsedId++;
    }

//    public void createNote(){
//
//    }

    public Note getNote(Long noteId) {
        //ищем элемент с таким id
        //если не нашли то делаем throw new IllegalArgumentException("unknown noteId = "+noteId);
    }
}

```

2019-07-25 13:20 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +public class WriteNotesActivity extends AppCompatActivity {
Давай мы пока не будем этот класс трогать, все остальное сначала поправим а потом сюда вернемся. Как только у нас будет нормально и удобно работать NotesRepository тут все станет прям намного лучше

2019-07-25 13:20 UTC, grenni2007 commented on app/src/main/res/layout/activity_notes.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
тут FrameLayout лишний пусть сразу ListView идет

2019-07-25 13:20 UTC, grenni2007 commented on app/src/main/res/menu/savemenu.xml
> +        android:id="@+id/itemMenuSave"
save_action

2019-07-25 13:20 UTC, grenni2007 commented on app/src/main/res/values/strings.xml
> +    <string name="DELETE">DELETE</string>
Ой не надо имена строк так называть, проверь все имена выше тоже

2019-07-25 13:59 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    public static HashMap<Long, Note> getDateBase() {
Сделал

2019-07-25 13:59 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    private static HashMap<Long, Note> dateBase = new HashMap<>();
Long- дата. вторую дату удалил

2019-07-25 14:03 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    private static SettingsManager settingsManager;
А как тогда мы будем получать эту переменную в NewPassActivity?

2019-07-25 14:04 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    private static SettingsManager settingsManager;
через Extra?

2019-07-25 14:06 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    public static SettingsManager getSettingsManager() {
как обращаться через  Extras?

2019-07-25 14:07 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    private String passDoc = "temp";
удалил

2019-07-25 14:13 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    public static ArrayList mData;
Сделай просто List< Note > - а как их потом сортировать?

2019-07-25 14:13 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    public static ArrayList mData;
ОГО, а зачем static то? убирай static - убрать static и добавить getMDate()?

2019-07-25 14:17 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    public MapAdapter(Map<Long, Note> map) {
не понял...( ArrayList<Note>? а куда long, во внутр Note?

2019-07-25 14:18 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yy hh:mm");
Сделал

2019-07-25 14:20 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +    private SettingsManager settingsManager = MainActivity.getSettingsManager();
А не будут ли созданы два разных объекта  с разными списками паролей?

2019-07-25 14:23 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NewPassActivity.java
> +    private SettingsManager settingsManager = MainActivity.getSettingsManager();
Сделал, работает. Но почему это воспринимается как один объект? Это singleton?

2019-07-25 14:24 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Note.java
> +    long calendar;
Уже удалил long calendar, оставил int checkBoxIsChecked

2019-07-25 14:26 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    private int impText = 0;
какое impText ? это же флажок который мы передаем в WriteNotesActivity

2019-07-25 14:31 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    public FloatingActionButton add;
Поправил

2019-07-26 09:28 UTC, kiselevgleb commented on app/src/main/res/layout/activity_write_notes.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Сделал

2019-07-26 09:31 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    @RequiresApi(api = Build.VERSION_CODES.M)
Удалил

2019-07-26 09:31 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    public void check() {
ок

2019-07-26 09:32 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        @RequiresApi(api = Build.VERSION_CODES.M)
ок

2019-07-26 09:33 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +                    startActivity(intent2);
Да, потому что список нужно обновить

2019-07-26 09:33 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/WriteNotesActivity.java
> +                startActivity(intent);
Да, потому что список нужно обновить

2019-07-26 09:34 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Note.java
> +    int checkBox;
Переименовал

2019-07-26 10:50 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +                intent.putExtra("haderEditText", note.getTitle());
Сделал

2019-07-26 10:53 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +    private static HashMap<Long, Note> dateBase = new HashMap<>();
Сделал так:
long - дата последнего редактирования (для сортировки)
Note(заголовок, текст, дедлайн, чекбокс)

2019-07-26 10:56 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    public static SettingsManager getSettingsManager() {
Сделал. SharedPreferences это singleton?

2019-07-26 10:56 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    private static SettingsManager settingsManager;
Сделал. SharedPreferences это singleton?

2019-07-26 10:58 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    public static ArrayList mData;
Удалил static. Обращаюсь через переменную класса.

2019-07-26 11:03 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    public MapAdapter(Map<Long, Note> map) {
Сделал

2019-07-26 11:05 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +        MapAdapter adapter = new MapAdapter(not);
ок

2019-07-26 11:19 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesAct.java
> +            intent.putExtra("impText", impText);
Сделал

2019-07-26 11:21 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +public class NotesRepository {
Уже реализовал, но чуть по-другому

2019-07-26 11:29 UTC, kiselevgleb commented on app/src/main/res/layout/activity_notes.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Что-то ошибка получилась((

2019-07-26 11:30 UTC, kiselevgleb commented on app/src/main/res/menu/savemenu.xml
> +        android:id="@+id/itemMenuSave"
сделал

2019-07-26 11:31 UTC, kiselevgleb commented on app/src/main/res/values/strings.xml
> +    <string name="DELETE">DELETE</string>
А что в них не так?

2019-08-12 10:49 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        @RequiresApi(api = Build.VERSION_CODES.M)
Как было `RequiresApi ` так и  осталось, нужно убрать

2019-08-12 10:49 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    private View.OnClickListener clickListenerC = new View.OnClickListener() {
перенести вверх к полям

2019-08-12 10:49 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    public void check() {
private

2019-08-12 10:49 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/Note.java
> +    String title;
А это?

2019-08-12 10:49 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +    public static HashMap<Long, Note> getNotes() {
Вот тут корень всех проблем с `Map<Long, Note>` которые у тебя по всему коду разбрелись.
Тебе нужно возвращать `List<Note>`

2019-08-12 14:34 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
>      String pass = "";
Поле поправил.
При добавлении saveInstanceState появляется ошибка RuntimeException: Parcel(((

2019-08-12 14:35 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    public ArrayList mData;
mData меняем, нельзя private final

2019-08-12 14:37 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    public ArrayList mData;
ArrayList<Map.Entry<Long,Note>> поправил

2019-08-12 14:37 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yy hh:mm");
Поправил

2019-08-12 14:37 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +        @RequiresApi(api = Build.VERSION_CODES.M)
Удалил

2019-08-12 14:37 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    private View.OnClickListener clickListenerC = new View.OnClickListener() {
перенес

2019-08-12 14:38 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    public void check() {
Поправил

2019-08-12 14:39 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +    public static HashMap<Long, Note> getNotes() {
А как же тогда сортировка?

2019-08-14 11:01 UTC, ghost requested changes
В NotesRepository
Еще раз) Внутри храни Map<Long, Note> где ключ это id
и добавь поле id в Note
А вот снаружи ты уже получаешь список который из этой map получаешь и сортируешь

2019-08-14 11:01 UTC, grenni2007 commented on app/src/main/res/values/strings.xml
> +    <string name="DELETE">DELETE</string>
имена строк должны называться  `pass_error` а не `PASS_ERROR` или `PassError`

2019-08-14 11:01 UTC, grenni2007 commented on app/src/main/res/layout/activity_notes.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
что говорит?

2019-08-15 11:34 UTC, ghost requested changes
Давай мы ничего пока кроме класса Note и NoteRepository трогать вообще сейчас не будем. Сначала их в порядок приведем

2019-08-15 11:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +    @RequiresApi(api = Build.VERSION_CODES.N)
RequiresApi говорит о том что если запустить этот код на API ниже Android N то он упадет с ошибкой

2019-08-15 11:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +            if (notes.get(i).getDeadline() < 34712658000000L) {
Эм, сделай свой компаратор, в нем смотри сначала на deadline а потом на все что хочешь.

2019-08-15 11:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +            if (notes.get(i).getDeadline() == noteId) {
Это очень плохая идея использовать Deadline как id.
никто не гарантирует что Deadline уникален. И что если его не будет?

2019-08-15 11:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/Note.java
> +    long deadline;
Сделай `Long deadline` и храни там null если дедлайн не установили

2019-08-15 11:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/Note.java
> +public class Note implements Serializable {
А где еще время последнего изменения?

2019-08-15 11:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +    public static void sort() {
не нужно делать public

2019-08-15 11:34 UTC, grenni2007 commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +    public static ArrayList<Note> notes = new ArrayList<>();
private

2019-08-15 13:02 UTC, kiselevgleb commented on app/build.gradle
> +    compileOptions {
Поправил

2019-08-15 13:02 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MainActivity.java
> +    private static final String COLOR1 = "COLOR1";
Удалил

2019-08-15 13:05 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    public MapAdapter(ArrayList list) {
Добавил

2019-08-15 13:07 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/MapAdapter.java
> +    public ArrayList<Note> mData;
Не понял... Исправить ArrayList<Note> на List<Note>?

2019-08-15 13:10 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Note.java
> +    int checkBoxIsChecked;
поменял

2019-08-15 13:12 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Note.java
> +    String title;
Поправил

2019-08-15 13:15 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +        notes.add(n);
нет, перед вызовом данного метода я всегда удаляю предыдущую запись

2019-08-15 13:24 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +    @RequiresApi(api = Build.VERSION_CODES.N)
Удалил

2019-08-15 13:25 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +            if (notes.get(i).getDeadline() < 34712658000000L) {
Сделал

2019-08-15 13:50 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +            if (notes.get(i).getDeadline() == noteId) {
Поправил

2019-08-15 13:52 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Note.java
> +    long deadline;
Так не могу, так как заметки у которых нет deadline тоже должны сортироваться между собой. Я им всем добавил дату сохранения\дату редактирования

2019-08-15 13:53 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/Note.java
> +public class Note implements Serializable {
В deadline у заметок без deadline. В заметках с deadline дата изменения не нужна

2019-08-15 13:54 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +    public static void sort() {
Поправил

2019-08-15 13:55 UTC, kiselevgleb commented on app/src/main/java/com/example/notesandreminding/NotesRepository.java
> +    public static ArrayList<Note> notes = new ArrayList<>();
Поправил

2019-08-30 14:21 UTC, ghost approved these changes

2019-08-30 14:22 UTC, merged